#!/usr/bin/env python3
"""Generate the Gazebo world (traffic_light_track.world) from track_path.

Places the 8x8 m track_ground and three low-profile traffic lights along
the painted course. Each light is positioned just beside the line and
yawed to face back toward the oncoming robot, so the top camera sees it
head-on. Light placements are derived from the same path used to paint
the texture, so they always line up.
"""
import math
import os

from track_path import GROUND_M, image_to_world, sample_path

# Fraction along the path (0..1) at which to place each light, the model to
# use, and which side of the line to stand on (+1 = left of travel dir).
LIGHTS = [
    {"s": 0.30, "model": "traffic_light_red", "name": "light_red_1", "side": -1},
    {"s": 0.55, "model": "traffic_light_green", "name": "light_green_1", "side": 1},
    {"s": 0.82, "model": "traffic_light_red", "name": "light_red_2", "side": -1},
]
SIDE_OFFSET_M = 0.35   # how far beside the line the post stands

WORLD_TEMPLATE = """<?xml version="1.0" ?>
<!-- AUTO-GENERATED by gen_world.py. Edit track_path.py / gen_world.py instead. -->
<sdf version="1.6">
  <world name="traffic_light_track">

    <include><uri>model://sun</uri></include>

    <physics type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.7 0.8 0.9 1</background>
      <shadows>false</shadows>
    </scene>

    <!-- 8x8 m track ground, centered at world origin. -->
    <include>
      <uri>model://track_ground</uri>
      <pose>0 0 0 0 0 0</pose>
    </include>

{lights}

    <gui fullscreen="0">
      <camera name="user_camera">
        <pose>0 -1 9 0 1.1 1.5708</pose>
        <view_controller>orbit</view_controller>
      </camera>
    </gui>

  </world>
</sdf>
"""

LIGHT_TEMPLATE = """    <include>
      <uri>model://{model}</uri>
      <name>{name}</name>
      <pose>{x:.4f} {y:.4f} 0 0 0 {yaw:.4f}</pose>
    </include>"""


def light_world_poses():
    """Return {name: (world_x, world_y, world_yaw)} for every configured light.

    Single source of truth shared by the world generator and the demo
    orchestrator (which respawns a light at the same pose).
    """
    pts = sample_path(n=2000)
    n = len(pts)
    poses = {}
    for cfg in LIGHTS:
        i = max(1, min(n - 2, int(cfg["s"] * (n - 1))))
        ix, iy = pts[i]
        # travel direction in image frame
        dx = pts[i + 1][0] - pts[i - 1][0]
        dy = pts[i + 1][1] - pts[i - 1][1]
        norm = math.hypot(dx, dy) or 1.0
        dx, dy = dx / norm, dy / norm
        # left-normal in image frame
        nx, ny = -dy, dx
        ox = ix + cfg["side"] * SIDE_OFFSET_M * nx
        oy = iy + cfg["side"] * SIDE_OFFSET_M * ny
        wx, wy = image_to_world(ox, oy)

        # Heading of travel in WORLD frame (world Y is flipped vs image).
        travel_yaw_world = math.atan2(-dy, dx)
        # Light should face the oncoming robot -> opposite of travel dir.
        face_yaw = travel_yaw_world + math.pi
        poses[cfg["name"]] = (wx, wy, face_yaw)
    return poses


def main():
    poses = light_world_poses()
    blocks = []
    for cfg in LIGHTS:
        wx, wy, face_yaw = poses[cfg["name"]]
        blocks.append(LIGHT_TEMPLATE.format(
            model=cfg["model"], name=cfg["name"], x=wx, y=wy, yaw=face_yaw,
        ))

    world = WORLD_TEMPLATE.format(lights="\n\n".join(blocks))
    out_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(
        out_dir, "..", "worlds", "traffic_light_track.world"
    )
    with open(out_path, "w") as f:
        f.write(world)
    print(f"Wrote world with {len(LIGHTS)} lights (ground {GROUND_M}x{GROUND_M}m) "
          f"to {out_path}")


if __name__ == "__main__":
    main()
